
export const GET_RESTAURANT_DATA = "GET_RESTAURANT_DATA";
// export const DELETE_PRODUCT_TO_CARD = "DELETE_PRODUCT_TO_CARD";
// export const GET_PRODUCTS = "GET_PRODUCTS";
// export const GET_PRODUCTS_ORDER_BY_PRICE_DESC = "GET_PRODUCTS_ORDER_BY_PRICE_DESC";
// export const GET_PRODUCTS_ORDER_BY_PRICE_ASC = "GET_PRODUCTS_ORDER_BY_PRICE_ASC"